PCVisAPP/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('', include('PointCloudManage.urls')),
    path('admin/', admin.site.urls)
]

PointCloudManage/urls.py
from django.urls import path, re_path
from django.views.generic import TemplateView

from PointCloudManage import views


app_name = 'PointCloudManage'


urlpatterns = [
    path('', views.index, name='index'),
    path('index/', views.index, name='index'),
    path('pcupsample-display-page/', views.pcupsample_display_page, name='pcupsample-display-page'),
    path('pcupsample-vis-page/<str:pc_name>/', views.pcupsample_vis_page, name='pcupsample-vis-page'),

    path('sceneupsample-display-page/', views.sceneupsample_display_page, name='sceneupsample-display-page'),
    path('sceneupsample-vis-page/', views.sceneupsample_vis_page, name='sceneupsample-vis-page'),

    path('segdataset-display-page/', views.segdataset_display_page, name='segdataset-display-page'),
    path('segdataset-vis-page/', views.segdataset_vis_page, name='segdataset-vis-page'),

    path('sceneseg-display-page/', views.sceneseg_display_page, name='sceneseg-display-page'),
    path('sceneseg-vis-page/', views.sceneseg_vis_page, name='sceneseg-vis-page'),

    path('mypcbase-display-page/', views.mypcbase_display_page, name='mypcbase-display-page'),
    path('mypcbase-folder-display-page/', views.mypcbase_folder_display_page, name='mypcbase-folder-display-page'),
    path('mypcbase-upload-page/', views.mypcbase_upload_page, name='mypcbase-upload-page'),
    path('mypcbase-upload/', views.mypcbase_upload, name='mypcbase-upload'),
    path('mypcbase-delete/', views.mypcbase_delete, name='mypcbase-delete'),
    path('mypcbase-folder-delete-all/', views.mypcbase_folder_delete_all, name='mypcbase-folder-delete-all'),
    path('mypcbase-vis-page/<str:folder_name>/<str:pc_name>/', views.mypcbase_vis_page, name='mypcbase-vis-page'),
    path('mypcbase-save-ply-with-rgb/', views.mypcbase_save_ply_with_rgb, name='mypcbase-save-ply-with-rgb'),
    path('mypcbase-get-texture-path/', views.mypcbase_get_texture_path, name='mypcbase-get-texture-path'),
    path('mypcbase-upsample/', views.mypcbase_upsample, name='mypcbase-upsample'),
    path('mypcbase-vis-upsample-page/<str:folder_name>/<str:pc_name>/', views.mypcbase_vis_upsample_page, name='mypcbase-vis-upsample-page'),
    path('mypcbase-zip-all/', views.mypcbase_zip_all, name="mypcbase-zip-all"),
    path('mypcbase-folder-zip-all/', views.mypcbase_folder_zip_all, name="mypcbase-folder-zip-all"),
    path('mypcbase-clear-temp-dir/', views.mypcbase_clear_temp_dir, name='mypcbase-clear-temp-dir'),
    path('mypcbase-get-progress-val/', views.mypcbase_get_progress_val, name='mypcbase-get-progress-val'),
    path('mypcbase-create-folder/', views.mypcbase_create_folder, name='mypcbase-create-folder'),
    path('mypcbase-rename-folder/', views.mypcbase_rename_folder, name='mypcbase-rename-folder'),
    path('mypcbase-folder-move-pc/', views.mypcbase_folder_move_pc, name='mypcbase-folder-move-pc'),

    path('recyclebin-display-page/', views.recyclebin_display_page, name='recyclebin-display-page'),
    path('recyclebin-folder-display-page/', views.recyclebin_folder_display_page, name='recyclebin-folder-display-page'),
    path('recyclebin-delete/', views.recyclebin_delete, name='recyclebin-delete'),
    path('recyclebin-folder-delete-all/', views.recyclebin_folder_delete_all, name='recyclebin-folder-delete-all'),
    path('recyclebin-delete-all/', views.recyclebin_delete_all, name='recyclebin-delete-all'),
    path('recyclebin-restore/', views.recyclebin_restore, name='recyclebin-restore'),
    path('recyclebin-folder-restore-all/', views.recyclebin_folder_restore_all, name='recyclebin-folder-restore-all'),
    path('recyclebin-restore-all/', views.recyclebin_restore_all, name='recyclebin-restore-all'),
    path('test/', views.test, name='test'),
    re_path(r'[a-zA-Z0-9]', TemplateView.as_view(template_name='404.html')),
]

handler404 = TemplateView.as_view(template_name='404.html')

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">

  <title>Point Cloud Visualization Platform</title>
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  
  <!--
  <link rel="stylesheet" href="https://cdn.bootcdn.net/ajax/libs/twitter-bootstrap/3.3.6/css/bootstrap.min.css" />
  <link rel="stylesheet" href="https://cdn.bootcdn.net/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
  -->

  <link rel="stylesheet" href="{% static 'external/bootstrap.min.css' %}" />
  <link rel="stylesheet" href="{% static 'external/font-awesome-4.7.0/css/font-awesome.min.css' %}" />
  <link rel="stylesheet" href="{% static 'css/skins/skin-blue.css' %}" />
  <link rel="stylesheet" href="{% static 'css/base-conf.css' %}" />
  
</head>

<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">
  <header class="main-header">
    <a href="#" class="logo"></a>
    <nav class="navbar navbar-static-top" role="navigation">
      <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
      </a>
      <div class="navbar-custom-menu">
      </div>
    </nav>
  </header>

  <aside class="main-sidebar">
    <section class="sidebar">
      <ul class="sidebar-menu" data-widget="tree">
        <li class="header">导航栏</li>
        <li><a href="{% url 'PointCloudManage:index' %}"><i class="fa fa-user"></i> <span>主页</span></a></li>
        <li><a href="{% url 'PointCloudManage:pcupsample-display-page' %}"><i class="fa fa-television"></i> <span>点云上采样展示</span></a></li>
        <li><a href="{% url 'PointCloudManage:sceneupsample-display-page' %}"><i class="fa fa-adjust"></i> <span>场景上采样展示</span></a></li>
        <li><a href="{% url 'PointCloudManage:segdataset-display-page' %}"><i class="fa fa-print"></i> <span>分割数据集展示</span></a></li>
        <li><a href="{% url 'PointCloudManage:sceneseg-display-page' %}"><i class="fa fa-tags"></i> <span>场景分割展示</span></a></li>
        <li><a href="{% url 'PointCloudManage:mypcbase-upload-page' %}"><i class="fa fa-upload"></i> <span>点云模型上传</span></a></li>
        <li><a href="{% url 'PointCloudManage:mypcbase-display-page' %}"><i class="fa fa-folder"></i> <span>我的点云模型库</span></a></li>
        <li><a href="{% url 'PointCloudManage:recyclebin-display-page' %}"><i class="fa fa-trash"></i> <span>回收站</span></a></li>
      </ul>
    </section>
  </aside>

  <div class="content-wrapper">
    {% block breadcrumb %}{% endblock %}
    <section class="content container-fluid">
      {% block content %}{% endblock %}
    </section>

    <div class="modal fade" id="loading" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
          data-backdrop='static'>
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title" id="myModalLabel"><strong>提示</strong></h4>
                </div>
                <div class="modal-body">
                    <div id="progress-loading-box" class="progress progress-striped">
                      <div id="progress-bar-loading-box" class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width:0%">
                        0%
                      </div>
                    </div>
                    <div id="loading-body" class="alert alert-info"></div>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="succ-msg-box" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
             data-backdrop='static'>
          <div class="modal-dialog" role="document">
              <div class="modal-content">
                  <div class="modal-header">
                      <h4 class="modal-title" id="myModalLabel"><strong>提示</strong></h4>
                  </div>
                  <div class="modal-body">
                      <div class="alert alert-success" id="succ-msg-box-body"></div>
                      <div class="row">
                          <button type="button" class="btn btn-secondary col-xs-offset-10" id="succ-msg-box-btn">我知道了</button>
                      </div>
                  </div>
              </div>
          </div>
      </div>

      <div class="modal fade" id="err-msg-box" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
            data-backdrop='static'>
          <div class="modal-dialog" role="document">
              <div class="modal-content">
                  <div class="modal-header">
                      <h4 class="modal-title" id="myModalLabel"><strong>提示</strong></h4>
                  </div>
                  <div class="modal-body">
                      <div class="alert alert-danger" id="err-msg-box-body"></div>
                      <div class="row">
                          <button type="button" class="btn btn-secondary col-xs-offset-10" id="err-msg-box-btn">我知道了</button>
                      </div>
                  </div>
              </div>
          </div>
      </div>
  </div>

  <footer class="main-footer">
    <div class="pull-right hidden-xs">
    </div>
    <strong><a href="" target="_blank">三维模型可视化展示平台</a></strong>
  </footer>
</div>

<!-- 
<script src="https://cdn.bootcdn.net/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script src="https://cdn.bootcdn.net/ajax/libs/twitter-bootstrap/3.3.6/js/bootstrap.min.js"></script>
<script src="http://www.yanhuangxueyuan.com/threejs/build/three.min.js"></script>
<script src="http://www.yanhuangxueyuan.com/threejs/examples/js/controls/OrbitControls.js"></script>
<script src="http://www.yanhuangxueyuan.com/threejs/examples/js/loaders/OBJLoader.js"></script>
<script src="http://www.yanhuangxueyuan.com/threejs/examples/js/loaders/PLYLoader.js"></script> 
-->

<script src="{% static 'external/jquery.min.js' %}"></script>
<script src="{% static 'external/bootstrap.min.js' %}"></script>
<script src="{% static 'external/three.min.js' %}"></script>
<script src="{% static 'external/OrbitControls.js' %}"></script>
<script src="{% static 'external/OBJLoader.js' %}"></script>
<script src="{% static 'external/PLYLoader.js' %}"></script>
<script src="{% static 'js/base-conf.js' %}"></script>
<script src="{% static 'js/utils.js' %}"></script>
<script>
  $('#succ-msg-box-btn').click(function () {
    $('#succ-msg-box').modal('hide');
  });
  
  $('#err-msg-box-btn').click(function () {
    $('#err-msg-box').modal('hide');
  });
  
  $.ajax({
    url: '/mypcbase-clear-temp-dir/',
    type: 'GET',
    data: { 'limited_time': 1800 },
    dataType: 'JSON',
    success: function (data) {}
  });
</script>

{% block script %}{% endblock %}

</body>
</html>